name: Reusable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: surajshenoy/ActionPrep-Again/.github/workflows/Demonstration.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
     - run: |
          echo Add other actions to build,
          echo test, and deploy your project.
